/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/app/theme/theme-provider'
import { Toaster } from 'sonner'
import { SessionProvider } from 'next-auth/react'
import Client from '@/components/app/client/client'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'E-Library',
  description: 'Generated by create next app',
}

export default function RootLayout(props: any) {
  const { children } = props
  const { session } = props

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            <Client>{children}</Client>
          </ThemeProvider>
        </SessionProvider>{' '}
      </body>
    </html>
  )
}
